services:
  db_postgres:
    image: bitnami/postgresql:15.4.0
    container_name: db_postgres
    ports:
      - 5435:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgresql_data:
